export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SUCCESS_SIGN_IN = "SUCCESS_SIGN_IN";
export const FAILURE_SIGN_IN = "FAILURE_SIGN_IN";

export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const FAILURE_SIGN_UP = "FAILURE_SIGN_UP";

export const SUCCESS_SIGN_OUT = "SUCCESS_SIGN_OUT";

export const REQUEST_WORDS = "REQUEST_WORDS";
export const SUCCESS_WORDS = "SUCCESS_WORDS";
export const FAILURE_WORDS = "FAILURE_WORDS";

export const REQUEST_WORD = "REQUEST_WORD";
export const SUCCESS_WORD = "SUCCESS_WORD";
export const FAILURE_WORD = "FAILURE_WORD";

export const REQUEST_KNOWLEDGES = "REQUEST_KNOWLEDGES";
export const SUCCESS_KNOWLEDGES = "SUCCESS_KNOWLEDGES";
export const FAILURE_KNOWLEDGES = "FAILURE_KNOWLEDGES";

export const REQUEST_ACHIEVEMENT = "REQUEST_ACHIEVEMENT";
export const SUCCESS_ACHIEVEMENT = "SUCCESS_ACHIEVEMENT";
export const FAILURE_ACHIEVEMENT = "FAILURE_ACHIEVEMENT";

export const REQUEST_RANKING = "REQUEST_RANKING";
export const SUCCESS_RANKING = "SUCCESS_RANKING";
export const FAILURE_RANKING = "FAILURE_RANKING";

export const SET_FILTER = "SET_FILTER";
